name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      ## Cache not important
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Deps
        run: yarn install

      - name: Check types of a core package
        run: cd snow-splash && yarn tsd

      - name: Run tests of a core package
        run: cd snow-splash && yarn test

      - name: Check if a core package builds
        run: cd snow-splash && yarn build

      - name: Check types of a react package
        run: cd snow-splash-react && yarn tsd

      - name: Check if a react package builds
        run: cd snow-splash-react && yarn build
